name: github-actions
run-name: ${{ github.actor }} GitHub Actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: a-recipe
          MYSQL_USER: root
          MYSQL_PASSWORD: Admin12345
          MYSQL_ROOT_PASSWORD: Admin12345
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: server install
        working-directory: ./server
        run: npm install
      - name: server build
        working-directory: ./server
        run: npm run build
      - name: server test jest
        working-directory: ./server
        run: npm run test
      - name: server test e2e
        working-directory: ./server
        run: npm run test:e2e
