name: github-actions
run-name: ${{ github.actor }} GitHub Actions
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: mysql-action@v1.1
        with:
          mysql-version: '8.0'
      - name: server install
        working-directory: ./server
        run: npm install
      - name: server build
        working-directory: ./server
        run: npm run build
      - name: server test jest
        working-directory: ./server
        run: npm run test
      - name: server test e2e
        working-directory: ./server
        run: npm run test:e2e
